use interface::RPCInterfaceClient;
use tarpc::client::{Config};

use tarpc::tokio_serde::formats::Json;

pub mod solution;

pub async fn start_client() -> RPCInterfaceClient {
    let server_addr: &str = "127.0.0.1:8080";

    let transport = tarpc::serde_transport::tcp::connect(
        server_addr, 
        Json::default
    ).await.unwrap();

    // The client stub is generated by the #[tarpc::service] attribute in interface.
    return interface::RPCInterfaceClient::new(Config::default(), transport).spawn();
}